// Mock data - các phòng họp
export const mockMeetingRooms = [
  {
    id: 1,
    name: "Daily standup - ChatWave",
    host: "Minh Anh",
    members: 5,
    maxMembers: 10,
    status: "live", // live | scheduled | ended
    startTime: "09:00",
    duration: "15 phút",
    groupName: "Nhóm ChatWave",
  },
  {
    id: 2,
    name: "Review UI/UX Sprint 2",
    host: "Hùng",
    members: 3,
    maxMembers: 8,
    status: "live",
    startTime: "14:00",
    duration: "1 giờ",
    groupName: "Nhóm ChatWave",
  },
  {
    id: 3,
    name: "Brainstorm ý tưởng Q2",
    host: "Admin",
    members: 0,
    maxMembers: 12,
    status: "scheduled",
    startTime: "16:00",
    scheduledDate: "15/03/2025",
    groupName: "Nhóm Marketing",
  },
  {
    id: 4,
    name: "Catch-up với Tuấn",
    host: "Bạn",
    members: 1,
    maxMembers: 4,
    status: "ended",
    startTime: "11:00",
    endedAt: "11:45",
    groupName: null,
  },
  {
    id: 5,
    name: "Training React hooks",
    host: "Lan",
    members: 7,
    maxMembers: 15,
    status: "live",
    startTime: "10:00",
    duration: "45 phút",
    groupName: "Nhóm Dev",
  },
];
